### ISSUE TITLE
cannot build :/

### ISSUE THREAD

**Issue by AndreGoressi** [dayanch96/YTLite#219] opened 2024-10-29 07:00 UTC
### Describe the bug

```yaml
ipa is nit an zip file error
```

### Steps to reproduce

```yaml
ths steps from the build description
```

### Post Requisites

- [X] I have checked that a similar issue has not been reported before.
- [X] Verified the relevance of the project and the version you are using.
- [X] Provided a detailed description of the problem and have filled in all required fields.
- [X] I did not answer truthfully to **ALL** the above checkboxes.
- [X] By submitting this issue, **I confirm that I have filled in all the necessary fields and complied with the guidelines. Failure to comply may result in the issue being closed without discussion, and repeated violations may lead to restrict account from further participation.**

**Comment by AndreGoressi** [comment] 2024-10-29 18:17
but you need an decrypted .ipa fiel right ? can you send me screenshots how have setup your workflow ? and maabe an link for an website to download appstore apps as ipa file ?

**Comment by AndreGoressi** [comment] 2024-10-29 18:17
> Not sure it helps you, but just wanted to let you know that as a test just now I was able to compile without issue using the github actions feature.

but you need an decrypted .ipa fiel right ? can you send me screenshots how have setup your workflow ? and maabe an link for an website to download appstore apps as ipa file ?

**Comment by cybrnook** [comment] 2024-10-29 18:22
https://armconverter.com/decryptedappstore/us is a source for decrypted ipa's (amongst others). Then you can use any hosting service really to stage your IPA file online (litterbox is one). Generate the link for the IPA and paste it into your URL field in Actions: 
![image](https://github.com/user-attachments/assets/fdc62099-2472-488f-b871-9e538f33de01)


You need to first fork the project to build your own copy.

**Comment by AndreGoressi** [comment] 2024-10-29 18:24
> https://armconverter.com/decryptedappstore/us is a source for decrypted ipa's (amongst others). Then you can use any hosting service really to stage your IPA file online (litterbox is one). Generate the link for the IPA and paste it into your URL field in Actions: ![image](https://private-user-images.githubusercontent.com/22136734/381258982-fdc62099-2472-488f-b871-9e538f33de01.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyMjY1MTYsIm5iZiI6MTczMDIyNjIxNiwicGF0aCI6Ii8yMjEzNjczNC8zODEyNTg5ODItZmRjNjIwOTktMjQ3Mi00ODhmLWI4NzEtOWU1MzhmMzNkZTAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI5VDE4MjMzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwNjQ1ZmFkYjZhMmViODJlMDkyNmU3NDgzZWM2ZGZjNDNhZTU3NjYwMzA4NWRlZTg5NDE1OTczMDgyNGE2NzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.kJPWCikqfDGGrwLjiO-QIg4ijAfYo4yf9kNA5Dr6hC0)
> 
> You need to first fork the project to build your own copy.
> 
> I would suggest closing this as a BUG as it's more user error and not an actual bug.

and the link with the .ipa file ? the upload link /Direct link to ther decrypted .ipa file ? with or without https:// ?

**Comment by AndreGoressi** [comment] 2024-10-29 18:25
> > https://armconverter.com/decryptedappstore/us is a source for decrypted ipa's (amongst others). Then you can use any hosting service really to stage your IPA file online (litterbox is one). Generate the link for the IPA and paste it into your URL field in Actions: ![image](https://private-user-images.githubusercontent.com/22136734/381258982-fdc62099-2472-488f-b871-9e538f33de01.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyMjY1MTYsIm5iZiI6MTczMDIyNjIxNiwicGF0aCI6Ii8yMjEzNjczNC8zODEyNTg5ODItZmRjNjIwOTktMjQ3Mi00ODhmLWI4NzEtOWU1MzhmMzNkZTAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI5VDE4MjMzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwNjQ1ZmFkYjZhMmViODJlMDkyNmU3NDgzZWM2ZGZjNDNhZTU3NjYwMzA4NWRlZTg5NDE1OTczMDgyNGE2NzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.kJPWCikqfDGGrwLjiO-QIg4ijAfYo4yf9kNA5Dr6hC0)
> > You need to first fork the project to build your own copy.
> > I would suggest closing this as a BUG as it's more user error and not an actual bug.
> 
> and the link with the .ipa file ? the upload link /Direct link to ther decrypted .ipa file ? with or without https:// ?

lol i was yesterday on this website but didnt work :/

**Comment by cybrnook** [comment] 2024-10-29 18:27
I am not posting a link to a shared ipa file on this repo. Honestly that's the easiest part of this, if you are having troubles already with that then you may have an issue locally on your PC or something. A simple google search around and I am confident you can find your own copy of the ipa file.

**Comment by AndreGoressi** [comment] 2024-10-29 18:31
lol now works :) with litterbox thx

**Comment by AndreGoressi** [comment] 2024-10-29 18:31
with the toher file hoster dont work idk why

**Comment by cybrnook** [comment] 2024-10-29 18:32
I would suggest closing this as it is not a bug.

Glad you got it working.

**Comment by dayanch96** [comment] 2024-10-29 23:57
@AndreGoressi problem in your link to the ipa. you have to put direct link so that remote machine will be able to download it. otherwise it will give error that you see when it tries to inject tweak into 'nothing'

**Closed by dayanch96** 2024-10-29 23:57 UTC
Labels: bug
